// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb, TargetPlatform, defaultTargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkb-EKj3RC-DohKX3EmUGStVEiZ_bGweo',
    appId: '1:251836591298:web:1259032a1b7792f4d45f5b',
    messagingSenderId: '251836591298',
    projectId: 'rebuy-190',
    authDomain: 'rebuy-190.firebaseapp.com',
    databaseURL: 'https://rebuy-190.firebaseio.com',
    storageBucket: 'rebuy-190.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkb-EKj3RC-DohKX3EmUGStVEiZ_bGweo',
    appId: '1:251836591298:android:1259032a1b7792f4d45f5b',
    messagingSenderId: '251836591298',
    projectId: 'rebuy-190',
    databaseURL: 'https://rebuy-190.firebaseio.com',
    storageBucket: 'rebuy-190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkb-EKj3RC-DohKX3EmUGStVEiZ_bGweo',
    appId: '1:251836591298:ios:1259032a1b7792f4d45f5b',
    messagingSenderId: '251836591298',
    projectId: 'rebuy-190',
    databaseURL: 'https://rebuy-190.firebaseio.com',
    storageBucket: 'rebuy-190.firebasestorage.app',
    iosClientId: 'placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.example.rebuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkb-EKj3RC-DohKX3EmUGStVEiZ_bGweo',
    appId: '1:251836591298:macos:1259032a1b7792f4d45f5b',
    messagingSenderId: '251836591298',
    projectId: 'rebuy-190',
    databaseURL: 'https://rebuy-190.firebaseio.com',
    storageBucket: 'rebuy-190.firebasestorage.app',
    iosBundleId: 'com.example.rebuy',
  );
}
